export const ADD_CAMPAIGNS = 'ADD_CAMPAIGNS';
export const DELETE_CAMPAIGNS = 'DELETE_CAMPAIGNS';
export const SEARCH_CAMPAIGNS ='SEARCH_CAMPAIGNS';
export const EDIT_CAMPAIGNS = 'EDIT_CAMPAIGNS';
export const TOGGLE_BAN = "TOGGLE_BAN";
export const TOGGLE_TOP = "TOGGLE_TOP";
export const MULTIPLE_DELETE = "MULTIPLE_DELETE";


