
import { LikeGif, HahaGif, LoveGif, SadGif, WowGif, AngryGif, angryface, blankface, call, clap, confused,
  cool, cry, cwl, disappointed, doh, donttalktome, dream, drunk, dull, eg, envy, facepalm, fearful,
   festiveparty, finger, fingerscrossed,flushed, giggle, happy, happyeyes, hearteyes, hi, highfive,
    hungover, hysterical, idea, ill, inlove, kiss, laugh, lipssealed, listening, loudlycrying, loveearth,
     makeup, mmm, movember, nazar, nerdy, nod, party, pensive, puke, punch, relieved, rock, rofl,
sarcastic, selfie, selfiediwali, shake, shivering, shock, slap, sleepy, smile, smileeyes, smirk,
 smoke, speechless, stareyes, surprised, swear, sweat, sweatgrinning, talk, talktothehand, taur, tauri,
  think, tired, tmi, tongueout, ttm, unamused, upsidedownface, veryconfused, wait, waiting, wasntme,
   weary, whew, whistle, wink, winktongueout, wonder, worry, wtf, xd, yawn  } from '../../../assets/reactions/gif';

export default [
  { icon: LikeGif, name: 'like' },
  { icon: LoveGif, name: 'love' },
  { icon: WowGif, name: 'wow' },
  { icon: SadGif, name: 'sad' },
  { icon: HahaGif, name: 'haha' },
  { icon: AngryGif, name: 'angry' },
  { icon: angryface, name: 'angryface' },
  { icon: blankface, name: 'blankface' },
  { icon: call, name: 'call' },
  { icon: clap, name: 'clap' },
  { icon: confused, name: 'confused' },
  { icon: cool, name: 'cool' },
  { icon: cry, name: 'cry' },
  { icon: cwl, name: 'cwl' },
  { icon: disappointed, name: 'disappointed' },
  { icon: doh, name: 'doh' },
  { icon: donttalktome, name: 'donttalktome' },
  { icon: dream, name: 'dream' },
  { icon: drunk, name: 'drunk' },
  { icon: dull, name: 'dull' },
  { icon: eg, name: 'eg' },
  { icon: envy, name: 'envy' },
  { icon: facepalm, name: 'facepalm' },
  { icon: fearful, name: 'fearful' },
  { icon: festiveparty, name: 'festiveparty' },
  { icon: finger, name: 'finger' },
  { icon: fingerscrossed, name: 'fingerscrossed' },
  { icon: flushed, name: 'flushed' },
  { icon: giggle, name: 'giggle' },
  { icon: happy, name: 'happy' },
  { icon: happyeyes, name: 'happyeyes' },
  { icon: hearteyes, name: 'hearteyes' },
  { icon: hi, name: 'hi' },
  { icon: highfive, name: 'highfive' },
  { icon: hungover, name: 'hungover' },
  { icon: hysterical, name: 'hysterical' },
  { icon: idea, name: 'idea' },
  { icon: ill, name: 'ill' },
  { icon: inlove, name: 'inlove' },
  { icon: kiss, name: 'kiss' },
  { icon: laugh, name: 'laugh' },
  { icon: lipssealed, name: 'lipssealed' },
  { icon: listening, name: 'listening' },
  { icon: loudlycrying, name: 'loudlycrying' },
  { icon: loveearth, name: 'loveearth' },
  { icon: makeup, name: 'makeup' },
  { icon: mmm, name: 'mmm' },
  { icon: movember, name: 'movember' },
  { icon: nazar, name: 'nazar' },
  { icon: nerdy, name: 'nerdy' },
  { icon: nod, name: 'nod' },
  { icon: party, name: 'party' },
  { icon: pensive, name: 'pensive' },
  { icon: puke, name: 'puke' },
  { icon: punch, name: 'punch' },
  { icon: relieved, name: 'relieved' },
  { icon: rock, name: 'rock' },
  { icon: rofl, name: 'rofl' },
  { icon: sarcastic, name: 'sarcastic' },
  { icon: selfie, name: 'selfie' },
  { icon: selfiediwali, name: 'selfiediwali' },
  { icon: shake, name: 'shake' },
  { icon: shivering, name: 'shivering' },
  { icon: shock, name: 'shock' },
  { icon: slap, name: 'slap' },
  { icon: sleepy, name: 'sleepy' },
  { icon: smile, name: 'smile' },
  { icon: smileeyes, name: 'smileeyes' },
  { icon: smirk, name: 'smirk' },
  { icon: smoke, name: 'smoke' },
  { icon: speechless, name: 'speechless' },
  { icon: stareyes, name: 'stareyes' },
  { icon: surprised, name: 'surprised' },
  { icon: swear, name: 'swear' },
  { icon: sweat, name: 'sweat' },
  { icon: sweatgrinning, name: 'sweatgrinning' },
  { icon: talk, name: 'talk' },
  { icon: talktothehand, name: 'talktothehand' },
  { icon: taur, name: 'taur' },
  { icon: tauri, name: 'tauri' },
  { icon: think, name: 'think' },
  { icon: tired, name: 'tired' },
  { icon: tmi, name: 'tmi' },
  { icon: tongueout, name: 'tongueout' },
  { icon: ttm, name: 'ttm' },
  { icon: unamused, name: 'unamused' },
  { icon: upsidedownface, name: 'upsidedownface' },
  { icon: veryconfused, name: 'veryconfused' },
  { icon: wait, name: 'wait' },
  { icon: waiting, name: 'waiting' },
  { icon: wasntme, name: 'wasntme' },
  { icon: weary, name: 'weary' },
  { icon: whew, name: 'whew' },
  { icon: whistle, name: 'whistle' },
  { icon: wink, name: 'wink' },
  { icon: winktongueout, name: 'winktongueout' },
  { icon: wonder, name: 'wonder' },
  { icon: worry, name: 'worry' },
  { icon: wtf, name: 'wtf' },
  { icon: xd, name: 'xd' },
  { icon: yawn, name: 'yawn' }
];
