export const OPEN_CHAT = 'OPEN_CHAT';
export const CLOSE_CHAT = 'CLOSE_CHAT';
export const TOGGLE_CHAT = 'TOGGLE_CHAT';

export const PUSH_CHAT_ROOM = 'PUSH_CHAT_ROOM';
export const MAKE_ROOM_ACTIVE = 'MAKE_ROOM_ACTIVE';
export const MAKE_ROOM_INACTIVE = 'MAKE_ROOM_INACTIVE';
export const PUSH_CHAT_MESSAGE = 'PUSH_CHAT_MESSAGE';
export const PUSH_OLD_ROOM = 'PUSH_OLD_ROOM';
