export const OPEN_CHAT = 'OPEN_CHAT';
export const CLOSE_CHAT = 'CLOSE_CHAT';
export const TOGGLE_CHAT = 'TOGGLE_CHAT';

export const PUSH_CHAT_ROOMS = 'PUSH_CHAT_ROOMS';
export const MAKE_ROOM_ACTIVE = 'MAKE_ROOM_ACTIVE';
export const MAKE_ROOM_INACTIVE = 'MAKE_ROOM_INACTIVE';

export const PUSH_CHAT_MESSAGES = 'PUSH_CHAT_MESSAGES';
export const REACT_CHAT_MESSAGE = 'REACT_CHAT_MESSAGE';
export const DELETE_CHAT_MESSAGE = 'DELETE_CHAT_MESSAGE';

export const GONE_OFFLINE = 'GONE_OFFLINE';
